import Foundation

/// Represents a daily report generated by Notty.
struct DailyReport: Codable, Identifiable, Sendable {
    let id: String
    let date: String          // YYYY-MM-DD
    let style: ReportStyle
    let depth: ReportDepth
    let status: ReportStatus
    let htmlContent: String?
    let sourceNoteIds: [String]?
    let errorMessage: String?
    let createdAt: Date
    let updatedAt: Date
}

enum ReportStyle: String, Codable, CaseIterable, Sendable {
    case minimal = "minimal"
    case academic = "academic"
    case dashboard = "dashboard"
    case handwritten = "handwritten"

    var displayName: String {
        switch self {
        case .minimal: return "极简杂志"
        case .academic: return "学术报告"
        case .dashboard: return "数据仪表盘"
        case .handwritten: return "手写笔记"
        }
    }

    var icon: String {
        switch self {
        case .minimal: return "sparkles"
        case .academic: return "book.fill"
        case .dashboard: return "chart.bar.fill"
        case .handwritten: return "pencil.and.outline"
        }
    }
}

enum ReportDepth: String, Codable, CaseIterable, Sendable {
    case brief = "brief"
    case deep = "deep"
    case action = "action"

    var displayName: String {
        switch self {
        case .brief: return "速览版"
        case .deep: return "深度版"
        case .action: return "行动清单"
        }
    }

    var description: String {
        switch self {
        case .brief: return "5 分钟读完"
        case .deep: return "20 分钟深度阅读"
        case .action: return "只列 TODO"
        }
    }
}

enum ReportStatus: String, Codable, Sendable {
    case generating = "generating"
    case completed = "completed"
    case failed = "failed"
}
