CREATE TABLE "blog_posts" (
	"id" serial PRIMARY KEY NOT NULL,
	"source" text NOT NULL,
	"slug" text NOT NULL,
	"url" text NOT NULL,
	"title" text,
	"date" text,
	"source_label" text,
	"summary" text,
	"content" text,
	"one_liner" text,
	"summary_cn" text,
	"ecommerce_connection" text,
	"relevance" text,
	"first_seen_date" text,
	"last_seen_date" text,
	"analyzed" boolean DEFAULT false,
	"created_at_ts" timestamp DEFAULT now(),
	"updated_at_ts" timestamp DEFAULT now(),
	CONSTRAINT "blog_posts_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "conference_papers" (
	"id" serial PRIMARY KEY NOT NULL,
	"paper_key" text NOT NULL,
	"title" text NOT NULL,
	"authors" jsonb DEFAULT '[]'::jsonb,
	"abstract" text,
	"venue" text NOT NULL,
	"venue_full_name" text,
	"rank" text NOT NULL,
	"category" text,
	"year" integer,
	"publication_date" text,
	"doi" text,
	"url" text,
	"pdf_url" text,
	"citation_count" integer DEFAULT 0,
	"tldr" text,
	"keywords" jsonb DEFAULT '[]'::jsonb,
	"paper_type" text,
	"one_liner" text,
	"summary_cn" text,
	"core_contribution" text,
	"ecommerce_connection" text,
	"relevance" text,
	"source" text DEFAULT 'papers_cool',
	"first_seen_date" text,
	"last_seen_date" text,
	"analyzed" boolean DEFAULT false,
	"created_at_ts" timestamp DEFAULT now(),
	"updated_at_ts" timestamp DEFAULT now(),
	CONSTRAINT "conference_papers_paper_key_unique" UNIQUE("paper_key")
);
--> statement-breakpoint
CREATE TABLE "github_repos" (
	"id" serial PRIMARY KEY NOT NULL,
	"full_name" text NOT NULL,
	"owner" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"stars" integer DEFAULT 0,
	"forks" integer DEFAULT 0,
	"language" text,
	"topics" jsonb DEFAULT '[]'::jsonb,
	"url" text NOT NULL,
	"pushed_at" text,
	"repo_created_at" text,
	"one_liner" text,
	"positioning" text,
	"core_tech" text,
	"use_cases" text,
	"comparison" text,
	"watch_reason" text,
	"relevance" text,
	"first_seen_date" text,
	"last_seen_date" text,
	"seen_count" integer DEFAULT 1,
	"stars_history" jsonb DEFAULT '{}'::jsonb,
	"analyzed" boolean DEFAULT false,
	"created_at_ts" timestamp DEFAULT now(),
	"updated_at_ts" timestamp DEFAULT now(),
	CONSTRAINT "github_repos_full_name_unique" UNIQUE("full_name")
);
--> statement-breakpoint
CREATE TABLE "official_items" (
	"id" serial PRIMARY KEY NOT NULL,
	"source" text NOT NULL,
	"slug" text NOT NULL,
	"url" text NOT NULL,
	"title" text,
	"date" text,
	"category" text,
	"item_type" text DEFAULT 'article',
	"summary" text,
	"content" text,
	"one_liner" text,
	"summary_cn" text,
	"core_insight" text,
	"ecommerce_connection" text,
	"relevance" text,
	"sitemap_lastmod" text,
	"first_seen_date" text,
	"last_seen_date" text,
	"analyzed" boolean DEFAULT false,
	"created_at_ts" timestamp DEFAULT now(),
	"updated_at_ts" timestamp DEFAULT now(),
	CONSTRAINT "official_items_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "papers" (
	"id" serial PRIMARY KEY NOT NULL,
	"arxiv_id" text NOT NULL,
	"title" text NOT NULL,
	"authors" jsonb DEFAULT '[]'::jsonb,
	"abstract" text DEFAULT '',
	"abs_url" text NOT NULL,
	"pdf_url" text,
	"doi" text,
	"doi_url" text,
	"published" text,
	"bibtex" text,
	"affiliations" jsonb DEFAULT '[]'::jsonb,
	"primary_image_url" text,
	"trans_abs" text DEFAULT '',
	"compressed" text DEFAULT '',
	"keywords" jsonb DEFAULT '[]'::jsonb,
	"sub_topic" text DEFAULT '未知',
	"recommendation" text DEFAULT '一般推荐',
	"one_liner" text,
	"core_recommendation" text,
	"status" text DEFAULT 'pending',
	"error_message" text,
	"processed_at" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp,
	CONSTRAINT "papers_arxiv_id_unique" UNIQUE("arxiv_id")
);
--> statement-breakpoint
CREATE TABLE "wechat_articles" (
	"id" serial PRIMARY KEY NOT NULL,
	"article_id" text NOT NULL,
	"title" text NOT NULL,
	"url" text NOT NULL,
	"mp_id" text NOT NULL,
	"mp_name" text,
	"publish_time" text,
	"author" text,
	"summary" text,
	"content" text,
	"cover_url" text,
	"one_liner" text,
	"summary_cn" text,
	"keywords" jsonb DEFAULT '[]'::jsonb,
	"core_recommendation" text,
	"relevance" text,
	"first_seen_date" text,
	"last_seen_date" text,
	"analyzed" boolean DEFAULT false,
	"created_at_ts" timestamp DEFAULT now(),
	"updated_at_ts" timestamp DEFAULT now(),
	CONSTRAINT "wechat_articles_article_id_unique" UNIQUE("article_id")
);
--> statement-breakpoint
CREATE INDEX "blog_posts_source_idx" ON "blog_posts" USING btree ("source");--> statement-breakpoint
CREATE INDEX "conference_papers_venue_idx" ON "conference_papers" USING btree ("venue");--> statement-breakpoint
CREATE INDEX "github_repos_first_seen_idx" ON "github_repos" USING btree ("first_seen_date");--> statement-breakpoint
CREATE INDEX "official_items_source_idx" ON "official_items" USING btree ("source");--> statement-breakpoint
CREATE INDEX "papers_published_idx" ON "papers" USING btree ("published");--> statement-breakpoint
CREATE INDEX "wechat_articles_mp_id_idx" ON "wechat_articles" USING btree ("mp_id");