#!/usr/bin/env python3
"""直接通过 aone-km MCP (Streamable HTTP / JSON-RPC) 上传当日 MD 日报到钉钉知识库。

与 upload_dingtalk.sh 不同,本脚本不再嵌套启动本地 `claude -p`,
而是直接调用 MCP 的 createDingDocWorkspaceDoc 工具,适合无人值守的自动化流程。

用法:
    python3 scripts/upload_dingtalk_direct.py [YYYYMMDD]
不传日期则默认上传今天的报告。
"""
import json
import os
import sys
import urllib.request
from datetime import datetime

MCP_URL = os.environ.get("AONE_KM_MCP_URL", "https://mcp.alibaba-inc.com/aone-km/mcp")
MCP_TOKEN = os.environ.get("AONE_KM_TOKEN", "0DUpKcH-N09JMie0tTQE")
WORKSPACE_ID = os.environ.get("DING_WORKSPACE_ID", "nb9XJjQZAoR2lXyA")
PARENT_NODE_ID = os.environ.get("DING_PARENT_NODE_ID", "o14dA3GK8gQlkoYwcKYo6jPLV9ekBD76")

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _headers(session=None):
    h = {
        "Content-Type": "application/json",
        "Accept": "application/json, text/event-stream",
        "PRIVATE-TOKEN": MCP_TOKEN,
    }
    if session:
        h["Mcp-Session-Id"] = session
    return h


def _parse_body(content_type, raw):
    """兼容 application/json 与 text/event-stream 两种返回。"""
    if "text/event-stream" in content_type:
        for line in raw.splitlines():
            line = line.strip()
            if line.startswith("data:"):
                data = line[len("data:"):].strip()
                if data and data != "[DONE]":
                    return json.loads(data)
        raise RuntimeError(f"无法从 SSE 响应解析数据: {raw[:500]}")
    return json.loads(raw)


def _post(payload, session=None, notify=False):
    req = urllib.request.Request(
        MCP_URL, data=json.dumps(payload).encode("utf-8"),
        headers=_headers(session), method="POST",
    )
    resp = urllib.request.urlopen(req, timeout=120)
    sid = resp.headers.get("Mcp-Session-Id") or session
    if notify:  # 通知类请求无响应体
        return sid, None
    return sid, _parse_body(resp.headers.get("Content-Type", ""), resp.read().decode("utf-8"))


def _sanitize_for_dingtalk(content: str) -> str:
    """钉钉文档渲染器在内容含大量行内代码(反引号)时会静默丢弃整篇内容。

    去掉行内代码反引号（`llm_algorithm` → llm_algorithm）即可让大文档正常落库。
    """
    return content.replace("`", "")


def _trim_for_dingtalk(content: str, max_chars: int = 45000) -> str:
    """裁剪报告内容到钉钉文档可接受的大小（约 50K 上限）。"""
    if len(content) <= max_chars:
        return content

    lines = content.splitlines()

    # Find section boundaries
    part_starts = {}
    for i, line in enumerate(lines):
        if line.startswith('## Part '):
            part_starts[line] = i

    # If no sections found, truncate
    if len(part_starts) < 2:
        return content[:max_chars]

    # Build trimmed sections
    result = []
    part_keys = sorted(part_starts.items(), key=lambda x: x[1])

    for idx, (header, start) in enumerate(part_keys):
        end = part_keys[idx + 1][1] if idx + 1 < len(part_keys) else len(lines)
        section_lines = lines[start:end]
        section = '\n'.join(section_lines)

        # Part 2 (GitHub): keep only first 3 detailed analyses
        if 'Part 2' in header and 'GitHub' in header:
            glines = section.splitlines()
            gkept = []
            dc = 0
            for l in glines:
                if l.startswith('##### '):
                    dc += 1
                if dc <= 3:
                    gkept.append(l)
                elif not (l.startswith('##### ') or l.startswith('- **')):
                    pass  # skip detail lines for repos > 3
            section = '\n'.join(gkept)

        # Part 3 (Official): keep only table (first 30 items), cut deep analysis
        if 'Part 3' in header and '官方' in header:
            olines = section.splitlines()
            okept = []
            trows = 0
            indeep = False
            for l in olines:
                if l.startswith('| '):
                    trows += 1
                    if trows <= 22:  # header + sep + 20 items
                        okept.append(l)
                elif l.startswith('##### ') or l.startswith('#### 深度'):
                    indeep = True
                elif not indeep:
                    okept.append(l)
            section = '\n'.join(okept)

        result.append(section)

    # Add footer
    footer = ''
    for i in range(len(lines) - 1, max(0, len(lines) - 10), -1):
        if 'Generated by Ascan' in lines[i]:
            footer = '\n'.join(lines[i:])
            break

    final = '\n\n'.join(result) + '\n\n' + footer

    # If still too large, truncate
    if len(final) > max_chars:
        final = final[:max_chars]

    return final


def upload(date_str):
    md_path = os.path.join(PROJECT_DIR, "docs", f"Ascan-{date_str}.md")
    if not os.path.isfile(md_path):
        sys.exit(f"[ERROR] 找不到报告文件: {md_path}")

    with open(md_path, encoding="utf-8") as f:
        content = f.read()

    # 去除首行 H1 标题(钉钉会用文档名作为标题,避免重复)
    lines = content.splitlines()
    if lines and lines[0].lstrip().startswith("# "):
        lines = lines[1:]
        if lines and lines[0].strip() == "":
            lines = lines[1:]
    content = "\n".join(lines)

    doc_title = f"Ascan-{date_str}"
    content = _trim_for_dingtalk(content)
    content = _sanitize_for_dingtalk(content)
    print(f"[upload] {md_path} → 钉钉知识库 ({doc_title}), {len(content)} chars")

    # 1) initialize
    sid, init_res = _post({
        "jsonrpc": "2.0", "id": 1, "method": "initialize",
        "params": {"protocolVersion": "2024-11-05", "capabilities": {},
                   "clientInfo": {"name": "ascan-uploader", "version": "1.0"}},
    })
    if not sid:
        sys.exit("[ERROR] 未获取到 MCP session id")

    # 2) initialized notification
    _post({"jsonrpc": "2.0", "method": "notifications/initialized"}, session=sid, notify=True)

    # 3) tools/call createDingDocWorkspaceDoc
    _, call_res = _post({
        "jsonrpc": "2.0", "id": 2, "method": "tools/call",
        "params": {
            "name": "createDingDocWorkspaceDoc",
            "arguments": {
                "workspaceId": WORKSPACE_ID,
                "parentNodeId": PARENT_NODE_ID,
                "name": doc_title,
                "docType": "DOC",
                "content": content,
            },
        },
    }, session=sid)

    if "error" in call_res:
        sys.exit(f"[ERROR] 创建文档失败: {json.dumps(call_res['error'], ensure_ascii=False)}")

    result = call_res.get("result", {})
    if result.get("isError"):
        text = " ".join(c.get("text", "") for c in result.get("content", []))
        sys.exit(f"[ERROR] 创建文档失败: {text}")

    # 提取 docKey
    doc_key = None
    for c in result.get("content", []):
        if c.get("type") == "text":
            print(c["text"])
            try:
                data = json.loads(c["text"])
                doc_key = data.get("data", {}).get("docKey")
            except json.JSONDecodeError:
                pass

    # 4) 用 updateDingDocContent 二次确认内容写入（createDingDocWorkspaceDoc 大内容可能静默丢失）
    if doc_key:
        _, update_res = _post({
            "jsonrpc": "2.0", "id": 3, "method": "tools/call",
            "params": {
                "name": "updateDingDocContent",
                "arguments": {
                    "docKey": doc_key,
                    "content": content,
                },
            },
        }, session=sid)
        if "error" in update_res:
            print(f"[warn] updateDingDocContent 失败: {json.dumps(update_res['error'], ensure_ascii=False)[:200]}")
        else:
            inner_ok = True
            for c in update_res.get("result", {}).get("content", []):
                if c.get("type") == "text":
                    try:
                        if json.loads(c["text"]).get("status") == "error":
                            inner_ok = False
                            print(f"[warn] updateDingDocContent 返回错误: {c['text'][:200]}")
                    except json.JSONDecodeError:
                        pass
            if inner_ok:
                print("[upload] updateDingDocContent 成功")
    else:
        print("[warn] 未获取到 docKey，跳过 updateDingDocContent")

    print("[upload] 上传成功")


if __name__ == "__main__":
    date_arg = sys.argv[1] if len(sys.argv) > 1 else datetime.now().strftime("%Y%m%d")
    upload(date_arg)
